name: AI Auto-Fixer
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

jobs:
  diagnose:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Download Logs
        uses: actions/download-artifact@v4
        with:
          name: build-log-${{ github.event.workflow_run.id }}

      - name: Analyze Error
        id: analyze
        run: |
          ERROR=$(grep -m1 -oP 'error: \K.*|make\[.*\]: \*\*\* \K.*' build.log)
          echo "error=$ERROR" >> $GITHUB_OUTPUT

      - name: Create Fix Branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/auto-fix/${Date.now()}`,
              sha: context.sha
            })

      - name: Propose Fix
        run: |
          sed -i '/TEST_ERROR_2/d' drivers/Makefile
          git add .
          git commit -m "Auto-fix: Remove test error"
          git push origin HEAD
