name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip

      - name: Setup Kconfig Files
        run: |
          # Create directories
          sudo mkdir -p kernel/sched_assist
          sudo mkdir -p kernel/locking/klockopt
          
          # Create sched_assist Kconfig
          cat > kernel/sched_assist/Kconfig << 'EOL'
          config OPLUS_FEATURE_SCHED_ASSIST
            tristate "sched_assist"
            default n
            help
              turning sched for ui, render and so on to improve UX

          config OPLUS_FEATURE_SCHED_SPREAD
            bool "sched_spread"
            default n
            help
              This is the uifirst 5.0 feature, which will spread tasks,
              kick runnable time from task demand and adjust bg's time slice.

          config OPLUS_FEATURE_AUDIO_OPT
            bool "config audio opt"
            default n
            help
              audio task schedule opt

          config MMAP_LOCK_OPT
            bool "config mmap lock opt"
            default n
            depends on OPLUS_FEATURE_SCHED_ASSIST
            help
              reduce sleep time in mmap lock

          config OPLUS_ALLBOOST_OPT
            bool "config allboost opt"
            default n
            help
              Make the SCHED_ALL_BOOST function take effect

          config OPLUS_FG_BOOST
            bool "config oplus fg boost"
            default n
            help
              Make the SCHED_FG_BOOST function take effect
          EOL
          
          # Create klockopt Kconfig
          cat > kernel/locking/klockopt/Kconfig << 'EOL'
          config KERNEL_LOCK_OPT
            tristate "config kernel lock opt"
            default n
            help
              uxmutex inplement & record rwsem owners
          EOL
          
          # Set permissions
          sudo chown -R $USER:$USER kernel/
          
          # Debug: Show created files
          echo -e "\nCreated Kconfig files:"
          ls -la kernel/sched_assist/
          ls -la kernel/locking/klockopt/

      - name: Configure Build
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Use MTK debug config
          echo "Using k6891v1_64_k419_debug_defconfig"
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k6891v1_64_k419_debug_defconfig
          
          # Show config
          echo -e "\nConfiguration summary:"
          head -n 50 out/.config

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Build with detailed output
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc) V=1 2>&1 | tee build.log
          
          BUILD_STATUS=${PIPESTATUS[0]}
          if [ $BUILD_STATUS -eq 0 ]; then
            echo "Build completed successfully!"
          else
            echo "Build failed with status $BUILD_STATUS"
            echo "Last 50 lines of build log:"
            tail -n 50 build.log
            echo -e "\nKconfig related errors:"
            grep -i "kconfig" build.log || true
            exit $BUILD_STATUS
          fi

      - name: Upload Build Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-outputs
          path: |
            out/.config
            build.log
            out/arch/arm64/boot/Image*
            kernel/sched_assist/Kconfig
            kernel/locking/klockopt/Kconfig
          if-no-files-found: warn
