name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Analyze Repository Structure
        run: |
          echo "=== Repository Analysis ==="
          echo "1. Current Directory:"
          pwd
          
          echo -e "\n2. Root Contents:"
          ls -la
          
          echo -e "\n3. Looking for existing sched_assist:"
          find . -name "sched_assist" -type d
          
          echo -e "\n4. Looking for existing klockopt:"
          find . -name "klockopt" -type d
          
          echo -e "\n5. Looking for all Kconfig files:"
          find . -name "Kconfig"
          
          echo -e "\n6. Checking vendors directory:"
          ls -la vendor/ 2>/dev/null || echo "No vendor directory"
          
          echo -e "\n7. Checking drivers directory:"
          ls -la drivers/ 2>/dev/null || echo "No drivers directory"
          
          echo -e "\n8. Checking kernel directory:"
          ls -la kernel/ 2>/dev/null || echo "No kernel directory"
          
          echo -e "\n9. Full path of any existing sched_assist:"
          readlink -f $(find . -name "sched_assist" -type d) 2>/dev/null || echo "No sched_assist found"
          
          echo -e "\n10. Directory tree (limited depth):"
          tree -L 3 2>/dev/null || echo "Tree command not found"
          
          echo -e "\n=== Analysis Complete ==="

      - name: Install Tree
        run: sudo apt-get install -y tree

      - name: Detailed Directory Analysis
        run: |
          echo "=== Detailed Analysis ==="
          
          echo -e "\n1. Full directory tree of important paths:"
          tree -L 4 kernel/ 2>/dev/null || echo "No kernel directory"
          tree -L 4 drivers/ 2>/dev/null || echo "No drivers directory"
          tree -L 4 vendor/ 2>/dev/null || echo "No vendor directory"
          
          echo -e "\n2. All symlinks in repository:"
          find . -type l -ls
          
          echo -e "\n3. All Kconfig files with contents:"
          for f in $(find . -name "Kconfig"); do
            echo -e "\nFile: $f"
            echo "===================="
            cat "$f" 2>/dev/null || echo "Cannot read file"
          done
          
          echo -e "\n=== Analysis Complete ==="

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: repository-analysis
          path: |
            repository-analysis.txt
            directory-analysis.txt
          if-no-files-found: warn
