name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip \
          libncurses-dev gzip python-is-python3

      - name: Verify and Setup Directories
        run: |
          # Function to create directory and files if they don't exist
          setup_dir() {
            local dir=$1
            if [ ! -d "$dir" ]; then
              echo "Creating directory: $dir"
              mkdir -p "$dir"
            else
              echo "Directory already exists: $dir"
            fi
          }
          
          # List of directories to check/create
          DIRS=(
            "kernel/sched_assist"
            "kernel/locking/klockopt"
            "arch/arm64/kernel/rootguard"
            "drivers/oplus/system"
          )
          
          # Verify/create each directory
          for dir in "${DIRS[@]}"; do
            setup_dir "$dir"
          done
          
          # Create or update OplusKernelEnvConfig.mk
          if [ ! -f "OplusKernelEnvConfig.mk" ]; then
            echo "Creating OplusKernelEnvConfig.mk"
            cat << 'EOL' > OplusKernelEnvConfig.mk
          # OPLUS Features Configuration
          OPLUS_FEATURE_HEALTHINFO=yes
          OPLUS_FEATURE_SCHED_ASSIST=yes
          OPLUS_FEATURE_TASK_CPUSTATS=yes
          OPLUS_FEATURE_HANS_FREEZE=yes
          OPLUS_FEATURE_STORAGE_TOOL=yes
          OPLUS_FEATURE_MMC_DRIVER=yes
          OPLUS_FEATURE_UFS_DRIVER=yes
          OPLUS_FEATURE_UFS_SHOW_LATENCY=yes
          OPLUS_FEATURE_AOD=yes
          OPLUS_FEATURE_DC=yes
          OPLUS_FEATURE_ENABLE_MODEM_DB=yes
          OPLUS_FEATURE_ENGINEERTOOLS=yes
          OPLUS_FEATURE_THEIA=yes
          OPLUS_FEATURE_APP_MONITOR=yes
          OPLUS_FEATURE_MULTI_KSWAPD=yes
          OPLUS_FEATURE_PHOENIX=yes
          OPLUS_FEATURE_SENSOR=yes
          OPLUS_FEATURE_IOMONITOR=yes
          OPLUS_FEATURE_MEMLEAK_DETECT=yes
          OPLUS_FEATURE_WIFI_MTUDETECT=yes
          OPLUS_FEATURE_WIFI_SLA=yes
          OPLUS_FEATURE_CHG_BASIC=yes

          # Export features
          $(foreach myfeature,$(shell grep OPLUS_FEATURE_ $(CURDIR)/OplusKernelEnvConfig.mk | grep -v "#" | cut -d'=' -f1), \
          $(eval $(myfeature)_MACRO := -D$(myfeature)) \
          $(eval KBUILD_CFLAGS += $($(myfeature)_MACRO)))
          
          export KBUILD_CFLAGS
          EOL
          else
            echo "OplusKernelEnvConfig.mk already exists"
          fi
          
          # Create or verify Kconfig files
          if [ ! -f "kernel/sched_assist/Kconfig" ]; then
            echo "Creating sched_assist Kconfig"
            cat << 'EOL' > kernel/sched_assist/Kconfig
          config OPLUS_FEATURE_SCHED_ASSIST
            tristate "sched_assist"
            default y
            help
              Config for sched assist
          
          config OPLUS_FEATURE_SCHED_SPREAD
            bool "sched spread"
            default y
            help
              Config for sched spread
          
          if OPLUS_FEATURE_SCHED_ASSIST
          config OPLUS_FEATURE_HEALTHINFO
            bool "healthinfo"
            default y
            help
              Config for healthinfo
          endif
          EOL
          else
            echo "sched_assist Kconfig already exists"
          fi
          
          # Verify and list all critical files
          echo "=== Directory Structure ==="
          ls -R kernel/sched_assist/ || echo "sched_assist not found"
          ls -R kernel/locking/klockopt/ || echo "klockopt not found"
          ls -R arch/arm64/kernel/rootguard/ || echo "rootguard not found"
          ls -R drivers/oplus/system/ || echo "oplus system not found"
          
          echo "=== Critical Files ==="
          [ -f "OplusKernelEnvConfig.mk" ] && echo "✓ OplusKernelEnvConfig.mk exists" || echo "✗ OplusKernelEnvConfig.mk missing"
          [ -f "kernel/sched_assist/Kconfig" ] && echo "✓ sched_assist Kconfig exists" || echo "✗ sched_assist Kconfig missing"

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Include OplusKernelEnvConfig.mk
          if [ -f "OplusKernelEnvConfig.mk" ]; then
            cp OplusKernelEnvConfig.mk Makefile.oplus
            echo "include Makefile.oplus" >> Makefile
          else
            echo "ERROR: OplusKernelEnvConfig.mk not found!"
            exit 1
          fi
          
          # Clean build
          make mrproper
          
          # Configure kernel
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k6891v1_64_k419_debug_defconfig
          
          # Enable OPLUS features in config
          if [ -f "OplusKernelEnvConfig.mk" ]; then
            for feature in $(grep OPLUS_FEATURE_ OplusKernelEnvConfig.mk | grep -v "#" | cut -d'=' -f1); do
              echo "CONFIG_${feature}=y" >> out/.config
            done
          fi
          
          # Update config
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE olddefconfig
          
          # Build kernel
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc) 2>&1 | tee build.log

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-files
          path: |
            out/arch/arm64/boot/Image*
            build.log
            OplusKernelEnvConfig.mk
            out/.config
          if-no-files-found: warn

      - name: Upload Directory Structure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: directory-structure
          path: |
            kernel/sched_assist/
            kernel/locking/klockopt/
            arch/arm64/kernel/rootguard/
            drivers/oplus/system/
          if-no-files-found: warn
