name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip \
          libncurses-dev gzip python-is-python3

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          # Setup AnyKernel3 for Realme X7 Max
          cd AnyKernel3
          # Update anykernel.sh with device-specific values
          sed -i 's/do.devicecheck=1/do.devicecheck=1/g' anykernel.sh
          sed -i 's/device.name1=/device.name1=RMX3031/g' anykernel.sh
          sed -i 's/device.name2=/device.name2=RMX3033/g' anykernel.sh
          sed -i 's/device.name3=/device.name3=GTNeo/g' anykernel.sh
          sed -i 's/device.name4=/device.name4=GTNeo2T/g' anykernel.sh
          sed -i 's/device.name5=/device.name5=X7Max/g' anykernel.sh
          cd ..

      - name: Setup OPLUS Config
        run: |
          # Create OplusKernelEnvConfig.mk
          echo "Creating OplusKernelEnvConfig.mk..."
          cat << 'EOL' > OplusKernelEnvConfig.mk
          # OPLUS Features Configuration
          OPLUS_FEATURE_HEALTHINFO=yes
          OPLUS_FEATURE_SCHED_ASSIST=yes
          OPLUS_FEATURE_TASK_CPUSTATS=yes
          OPLUS_FEATURE_HANS_FREEZE=yes
          OPLUS_FEATURE_STORAGE_TOOL=yes
          OPLUS_FEATURE_MMC_DRIVER=yes
          OPLUS_FEATURE_UFS_DRIVER=yes
          OPLUS_FEATURE_UFS_SHOW_LATENCY=yes
          OPLUS_FEATURE_AOD=yes
          OPLUS_FEATURE_DC=yes
          OPLUS_FEATURE_ENABLE_MODEM_DB=yes
          OPLUS_FEATURE_ENGINEERTOOLS=yes
          OPLUS_FEATURE_THEIA=yes
          OPLUS_FEATURE_APP_MONITOR=yes
          OPLUS_FEATURE_MULTI_KSWAPD=yes
          OPLUS_FEATURE_PHOENIX=yes
          OPLUS_FEATURE_SENSOR=yes
          OPLUS_FEATURE_IOMONITOR=yes
          OPLUS_FEATURE_MEMLEAK_DETECT=yes
          OPLUS_FEATURE_WIFI_MTUDETECT=yes
          OPLUS_FEATURE_WIFI_SLA=yes
          OPLUS_FEATURE_CHG_BASIC=yes

          # Export features
          $(foreach myfeature,$(shell grep OPLUS_FEATURE_ $(CURDIR)/OplusKernelEnvConfig.mk | grep -v "#" | cut -d'=' -f1), \
          $(eval $(myfeature)_MACRO := -D$(myfeature)) \
          $(eval KBUILD_CFLAGS += $($(myfeature)_MACRO)))
          
          export KBUILD_CFLAGS
          EOL

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Copy OplusKernelEnvConfig.mk to Makefile.oplus
          cp OplusKernelEnvConfig.mk Makefile.oplus
          echo "include Makefile.oplus" >> Makefile
          
          # Clean build
          make mrproper
          
          # Configure kernel
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k6891v1_64_k419_debug_defconfig
          
          # Enable OPLUS features in config
          while IFS= read -r line; do
            if [[ $line =~ ^OPLUS_FEATURE_ && ! $line =~ ^# ]]; then
              feature=$(echo "$line" | cut -d'=' -f1)
              echo "CONFIG_${feature}=y" >> out/.config
            fi
          done < OplusKernelEnvConfig.mk
          
          # Update config
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE olddefconfig
          
          # Build kernel
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc) 2>&1 | tee build.log

      - name: Package Kernel
        run: |
          if [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
            # Copy kernel to AnyKernel3 directory
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
            
            # Create flashable ZIP
            cd AnyKernel3
            zip -r9 ../X7Max-Kernel-$(date +%Y%m%d).zip * -x .git README.md *placeholder
            cd ..
            
            echo "Kernel packaged successfully!"
          else
            echo "Error: Kernel image not found!"
            exit 1
          fi

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-files
          path: |
            out/arch/arm64/boot/Image*
            build.log
            OplusKernelEnvConfig.mk
            out/.config
            *.zip
          if-no-files-found: warn
