name: Build Kernel Module
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel
        uses: actions/checkout@v4
        with:
          repository: dharani-dp-33/realme_X7max_GTneo_GTneo2T-AndroidT-kernel-source
          fetch-depth: 0
          
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential libssl-dev make bc bison flex libelf-dev zip

      - name: Verify Repository Structure
        run: |
          echo "Checking repository structure..."
          echo "1. Checking arch/arm64/configs:"
          ls -la arch/arm64/configs/ || echo "configs directory not found"
          
          echo "2. Checking kernel/sched_assist:"
          ls -la kernel/sched_assist/ || echo "sched_assist directory not found"
          
          echo "3. Looking for any defconfig files:"
          find . -name "*defconfig" -type f
          
          echo "4. Checking main Kconfig:"
          cat init/Kconfig | grep -A 5 "sched_assist" || echo "No sched_assist in main Kconfig"
