name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip

      - name: Analyze Repository Structure
        run: |
          echo "Repository Structure Analysis:"
          echo "=============================="
          
          echo "1. Root directory contents:"
          ls -la
          
          echo -e "\n2. Kernel directory contents:"
          ls -la kernel/ || echo "No kernel directory"
          
          echo -e "\n3. Looking for symlinks:"
          find . -type l -exec ls -l {} \;
          
          echo -e "\n4. Looking for Kconfig files:"
          find . -name "Kconfig"
          
          echo -e "\n5. Directory tree of important paths:"
          tree kernel/ 2>/dev/null || echo "No kernel directory"
          tree drivers/android/ 2>/dev/null || echo "No android drivers"
          
          echo -e "\n6. Available defconfigs:"
          ls -la arch/arm64/configs/

      - name: Create Required Directories
        run: |
          # First check if directories exist
          echo "Current structure before creating directories:"
          pwd
          ls -la
          
          echo -e "\nAttempting to create directories:"
          # Try creating in vendor first
          mkdir -p vendor/oplus/kernel/oplus_performance/sched_assist || echo "Could not create in vendor"
          mkdir -p vendor/oplus/kernel/oplus_performance/locking/klockopt || echo "Could not create in klockopt"
          
          # Try creating in drivers as alternative
          mkdir -p drivers/oplus/kernel/oplus_performance/sched_assist || echo "Could not create in drivers"
          mkdir -p drivers/oplus/kernel/oplus_performance/locking/klockopt || echo "Could not create in drivers/klockopt"
          
          echo -e "\nFinal directory structure:"
          find . -name "sched_assist" -o -name "klockopt"

      - name: Upload Analysis Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repository-analysis
          path: |
            repository-structure.txt
            find-results.txt
          if-no-files-found: warn
