name: Package Kernel for Flashing
on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Info
        run: |
          echo "=== Build Information ==="
          echo "Date: 2025-03-23"
          echo "Time: 18:39:41"
          echo "User: dharani-dp-33"
          echo "Device: X7Max/GTNeo/GTNeo2T"

      - name: Download Previous Build
        uses: actions/download-artifact@v4
        with:
          name: kernel-build-and-test
          path: kernel-files

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip curl wget android-tools-adb

      - name: Create Flash Package
        run: |
          mkdir -p flash_package
          cd flash_package
          
          # Create flash instructions
          cat << 'EOF' > FLASH_INSTRUCTIONS.txt
          X7Max/GTNeo/GTNeo2T Kernel Flashing Instructions
          ==============================================
          Build Date: 2025-03-23
          Build Time: 18:39:41
          Builder: dharani-dp-33

          Prerequisites:
          -------------
          1. Unlocked bootloader
          2. Working recovery (TWRP recommended)
          3. USB debugging enabled
          4. Battery above 50%

          Flashing Steps:
          --------------
          Via Recovery (Recommended):
          1. Boot into recovery mode (Power + Vol Up)
          2. Select "Install"
          3. Navigate to X7Max-Kernel.zip
          4. Swipe to flash
          5. Reboot system

          Via Fastboot (Alternative):
          1. Boot into fastboot mode (Power + Vol Down)
          2. Run: fastboot flash boot Image.gz-dtb
          3. Run: fastboot reboot

          Notes:
          ------
          - Make backup before flashing
          - First boot may take longer
          - If boot fails, flash stock kernel
          EOF

          # Create changelog
          cat << 'EOF' > CHANGELOG.txt
          Kernel Build Changelog
          ====================
          Date: 2025-03-23
          Time: 18:39:41
          Builder: dharani-dp-33

          Changes:
          - Updated OPLUS features
          - Added scheduler configurations
          - Security patches implemented
          - Performance optimizations
          EOF

          # Create verification script
          cat << 'EOF' > verify_kernel.sh
          #!/bin/bash
          echo "Kernel Verification Script"
          echo "========================="
          echo "Checking kernel version..."
          adb shell cat /proc/version
          echo "Checking CPU frequency..."
          adb shell cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
          echo "Checking temperature..."
          adb shell cat /sys/class/thermal/thermal_zone*/temp
          EOF
          chmod +x verify_kernel.sh

      - name: Package Everything
        run: |
          cd flash_package
          
          # Copy kernel files
          cp ../kernel-files/out/arch/arm64/boot/Image.gz-dtb ./
          cp ../kernel-files/X7Max-Kernel.zip ./
          
          # Create final package
          zip -r ../X7Max-Kernel-Full.zip \
            * \
            -x "*.git*" \
            -x "*placeholder*"

      - name: Generate SHA256 Checksums
        run: |
          cd flash_package
          sha256sum Image.gz-dtb X7Max-Kernel.zip > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Upload Flash Package
        uses: actions/upload-artifact@v4
        with:
          name: X7Max-Kernel-Flash-Package
          path: |
            X7Max-Kernel-Full.zip
            flash_package/SHA256SUMS.txt
          if-no-files-found: error

      - name: Create Release Info
        run: |
          cat << EOF > release-info.txt
          X7Max/GTNeo/GTNeo2T Kernel Release
          ================================
          Build Date: 2025-03-23
          Build Time: 18:39:41
          Builder: dharani-dp-33

          Package Contents:
          - Kernel image (Image.gz-dtb)
          - AnyKernel3 flashable zip
          - Flashing instructions
          - Verification script
          - SHA256 checksums
          EOF

      - name: Upload Release Info
        uses: actions/upload-artifact@v4
        with:
          name: X7Max-Kernel-Release-Info
          path: release-info.txt
