name: Kernel Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip \
          libncurses-dev gzip python-is-python3

      - name: Fix Kconfig Structure
        run: |
          # Create missing klockopt directory and Kconfig
          mkdir -p kernel/locking/klockopt
          cat > kernel/locking/klockopt/Kconfig << 'EOF'
          config KLOCKOPT
            bool "Kernel Lock Optimization"
            default y
            help
              Enable kernel lock optimization features
          EOF

          # Verify the file was created
          echo "=== Verifying Kconfig Creation ==="
          cat kernel/locking/klockopt/Kconfig

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export KBUILD_BUILD_USER=dharani-dp-33
          export KBUILD_BUILD_HOST="github-actions"
          
          # Clean build directory
          rm -rf out/
          mkdir -p out/
          
          # Build with your specific defconfig
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k6891v1_64_k419_debug_defconfig
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc) 2>&1 | tee build.log

      - name: Upload Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            out/arch/arm64/boot/Image*
            build.log
            out/.config
          if-no-files-found: warn
