name: Kernel Tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Previous Build
        uses: actions/download-artifact@v4
        with:
          name: kernel-build-files
          path: kernel-files

      - name: Setup Test Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-aarch64 \
            libguestfs-tools \
            sparse \
            cppcheck \
            kmod

      - name: Update Build Info
        run: |
          echo "=== Build Information ==="
          echo "Date: 2025-03-23"
          echo "Time: 18:25:03"
          echo "User: dharani-dp-33"

      - name: Static Analysis
        run: |
          echo "=== Running Static Analysis ==="
          
          # Check kernel config
          if [ -f "kernel-files/out/.config" ]; then
            echo "Analyzing kernel config..."
            grep -i "CONFIG_DEBUG" kernel-files/out/.config || echo "No debug configs found"
            grep -i "CONFIG_SECURITY" kernel-files/out/.config || echo "No security configs found"
          fi
          
          # Check Image size
          if [ -f "kernel-files/out/arch/arm64/boot/Image.gz-dtb" ]; then
            echo "Kernel image size:"
            ls -lh kernel-files/out/arch/arm64/boot/Image.gz-dtb
          fi

      - name: Basic Module Tests
        run: |
          echo "=== Testing Kernel Modules ==="
          
          if [ -d "kernel-files/out/drivers" ]; then
            find kernel-files/out/drivers -name "*.ko" -exec file {} \;
          fi

      - name: Security Checks
        run: |
          echo "=== Running Security Checks ==="
          
          # Check for common security configurations
          if [ -f "kernel-files/out/.config" ]; then
            echo "Checking security configs..."
            for config in \
              CONFIG_SECURITY \
              CONFIG_SECCOMP \
              CONFIG_SECURITY_SELINUX \
              CONFIG_SECURITY_APPARMOR \
              CONFIG_DEFAULT_SECURITY; do
              grep -w $config kernel-files/out/.config || echo "$config not found"
            done
          fi

      - name: Generate Test Report
        run: |
          cat << EOF > test-report.txt
          Kernel Test Report
          =================
          Date: 2025-03-23
          Time: 18:25:03
          User: dharani-dp-33

          1. Build Verification
          --------------------
          - Image Size: $(ls -lh kernel-files/out/arch/arm64/boot/Image.gz-dtb 2>/dev/null || echo "Not found")
          - Config Present: $([ -f kernel-files/out/.config ] && echo "Yes" || echo "No")
          
          2. Security Checks
          ----------------
          $(grep -i "CONFIG_SECURITY" kernel-files/out/.config 2>/dev/null || echo "No security configs found")
          
          3. Module Information
          -------------------
          $(find kernel-files/out/drivers -name "*.ko" 2>/dev/null | wc -l) modules found
          EOF

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: kernel-test-results
          path: |
            test-report.txt
          if-no-files-found: warn
