name: Kernel Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc build-essential \
          libssl-dev make bc bison flex libelf-dev zip \
          libncurses-dev gzip python-is-python3

      - name: Fix Kconfig Structure
        run: |
          # Check actual Kconfig structure
          echo "=== Checking Kconfig Structure ==="
          find . -name "Kconfig" -type f -exec echo {} \;
          
          # Remove the problematic include from init/Kconfig
          if [ -f "init/Kconfig" ]; then
            sed -i '/kernel\/sched_assist\/Kconfig/d' init/Kconfig
          fi

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export KBUILD_BUILD_USER=dharani-dp-33
          export KBUILD_BUILD_HOST="github-actions"
          
          # Show current config
          echo "=== Current Configuration ==="
          ls -la arch/arm64/configs/
          
          # Attempt build
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k6891v1_64_k419_debug_defconfig
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc) 2>&1 | tee build.log

      - name: Upload Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            out/arch/arm64/boot/Image*
            build.log
            out/.config
            arch/arm64/configs/*_defconfig
          if-no-files-found: warn
